#!/bin/bash

cd ./build/libs/
FILE_NAME=`echo "ProgressiveAutomation-1.8.9-*"`
cd ../../
FILE_LOCATION=`echo "./build/libs/$FILE_NAME"`
CHANGE_LOG=`git log -1 --pretty=format:"%B"`

#See https://github.com/curseforge/api for how to retrieve game version numbers
JSON=`printf '{"changelog": "%s", "gameVersions": [5806], "releaseType": "alpha"}' "$CHANGE_LOG"`

echo "Uploading $FILE_NAME to Curse Forge..."
echo
RESPONSE=`curl -H "X-Api-Token: $CURSE_API_KEY" -X POST  -F metadata="$JSON"  -F file="@$FILE_LOCATION" https://minecraft.curseforge.com/api/projects/220606/upload-file`
echo
echo $RESPONSE